import type { Metadata } from 'next';
import { Header } from './app-header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <div className="md:mt-12 mt-6 pb-10 max-w-7xl w-full mx-auto">{children}</div>
    </>
  );
}
